CREATE TABLE BRANDS (
    ID BIGINT NOT NULL,
    NAME VARCHAR(60) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTS (
    ID BIGINT NOT NULL,
    NAME VARCHAR(60) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PRICES (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    BRAND_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CURR VARCHAR(3) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID)
);